spring:
  datasource:
    url: jdbc:mysql://localhost:3307/heroes_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: heroes
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  devtools:
    livereload:
      enabled: true
      port: 35730
server:
  servlet:
    context-path: /api/v1
  port: 8083