INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (1, 'Batman', 'DC', 'Bruce Wayne', 'Detective Comics #27');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (2, 'Superman', 'DC', 'Kal-El', 'Action Comics #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (3, 'Flash', 'DC', 'Jay Garrick', 'Flash Comics #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (4, 'Green Lantern', 'DC', 'Alan Scott', 'All-American Comics #16');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (5, 'Green Arrow', 'DC', 'Oliver Queen', 'More Fun Comics #73');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (6, 'Wonder Woman', 'DC', 'Princess Diana', 'All Star Comics #8');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (7, 'Martian Manhunter', 'DC', 'J"onn J"onzz', 'Detective Comics #225');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (8, 'Robin/Nightwing', 'DC', 'Dick Grayson', 'Detective Comics #38');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (9, 'Blue Beetle', 'DC', 'Dan Garret', 'Mystery Men Comics #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (10, 'Black Canary', 'DC', 'Dinah Drake', 'Flash Comics #86');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (11, 'Spider Man', 'MARVEL', 'Peter Parker', 'Amazing Fantasy #15');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (12, 'Captain America', 'MARVEL', 'Steve Rogers', 'Captain America Comics #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (13, 'Iron Man', 'MARVEL', 'Tony Stark', 'Tales of Suspense #39');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (14, 'Thor', 'MARVEL', 'Thor Odinson', 'Journey into Myster #83');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (15, 'Hulk', 'MARVEL', 'Bruce Banner', 'The Incredible Hulk #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (16, 'Wolverine', 'MARVEL', 'James Howlett', 'The Incredible Hulk #180');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (17, 'Daredevil', 'MARVEL', 'Matthew Michael Murdock', 'Daredevil #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (18, 'Hawkeye', 'MARVEL', 'Clinton Francis Barton', 'Tales of Suspense #57');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (19, 'Cyclops', 'MARVEL', 'Scott Summers', 'X-Men #1');
INSERT INTO hero (id, name, publisher, alter_ego, first_apparition) VALUES (20, 'Silver Surfer', 'MARVEL', 'Norrin Radd', 'The Fantastic Four #48');


INSERT INTO hero_characters (hero_id, characters) values ( 1, 'Bruce Wayne');
INSERT INTO hero_characters (hero_id, characters) values ( 2, 'Kal-El');
INSERT INTO hero_characters (hero_id, characters) values ( 2, 'Clark Kent');
INSERT INTO hero_characters (hero_id, characters) values ( 3, 'Jay Garrick');
INSERT INTO hero_characters (hero_id, characters) values ( 3, 'Barry Allen');
INSERT INTO hero_characters (hero_id, characters) values ( 3, 'Wally West');
INSERT INTO hero_characters (hero_id, characters) values ( 3, 'Bart Allen');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Alan Scott');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Hal Jordan');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Guy Gardner');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'John Stewart');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Kyle Raynor');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Jade');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Sinestro');
INSERT INTO hero_characters (hero_id, characters) values ( 4, 'Simon Baz');
INSERT INTO hero_characters (hero_id, characters) values ( 5, 'Oliver Queen');
INSERT INTO hero_characters (hero_id, characters) values ( 6, 'Princess Diana');
INSERT INTO hero_characters (hero_id, characters) values ( 7, 'Martian Manhunter');
INSERT INTO hero_characters (hero_id, characters) values ( 8, 'Dick Grayson');
INSERT INTO hero_characters (hero_id, characters) values ( 9, 'Dan Garret');
INSERT INTO hero_characters (hero_id, characters) values ( 9, 'Ted Kord');
INSERT INTO hero_characters (hero_id, characters) values ( 9, 'Jaime Reyes');
INSERT INTO hero_characters (hero_id, characters) values ( 10, 'Dinah Drake');
INSERT INTO hero_characters (hero_id, characters) values ( 10, 'Dinah Lance');
INSERT INTO hero_characters (hero_id, characters) values ( 11, 'Peter Parker');
INSERT INTO hero_characters (hero_id, characters) values ( 12, 'Steve Rogers');
INSERT INTO hero_characters (hero_id, characters) values ( 13, 'Tony Stark');
INSERT INTO hero_characters (hero_id, characters) values ( 14, 'Thor Odinson');
INSERT INTO hero_characters (hero_id, characters) values ( 15, 'Bruce Banner');
INSERT INTO hero_characters (hero_id, characters) values ( 16, 'James Howlett');
INSERT INTO hero_characters (hero_id, characters) values ( 17, 'Matthew Michael Murdock');
INSERT INTO hero_characters (hero_id, characters) values ( 18, 'Clinton Francis Barton');
INSERT INTO hero_characters (hero_id, characters) values ( 19, 'Scott Summers');
INSERT INTO hero_characters (hero_id, characters) values ( 20, 'Norrin Radd');
